# Generated by Django 4.0.3 on 2022-03-25 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=250, unique=True)),
                ('image', models.ImageField(null=True, upload_to='images')),
            ],
        ),
    ]
